### ISSUE TITLE
com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version.

### ISSUE THREAD

**Issue by minauser** [ConnectedHomes/sqs-kafka-connect#20]
When trying to run tests using
```
sbt clean test it:test
```
or running curl command

curl -X POST -H "Content-Type: application/json" -d '{
     "name": "aws-sqs-source",
     "config": {
         "connector.class": "com.hivehome.kafka.connect.sqs.SQSSourceConnector",
         "tasks.max": "1",
         "destination.topic": "kafka-topic-destination",
         "source.queue": "sqs-queue",
         "aws.region": "us-east-1"
} }' "http://<CONNECT_HOST>:<CONNECT_PORT>/connectors"

I get below error although the SQS queue (e.g. sqs-queue") already created in the specific region (e.g. "us-east-1"). 
I even tried the fully qualified name of the queue 
"https://sqs.us-east-1.amazonaws.com/868622222525/sqs-queue", same problem.

```
HTTPStatusCode: 400 AmazonErrorCode: AWS.SimpleQueueService.NonExistentQueue
    at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.handleException(AmazonSQSMessagingClientWrapper.java:391)
    at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.getQueueUrl(AmazonSQSMessagingClientWrapper.java:262)
    at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.getQueueUrl(AmazonSQSMessagingClientWrapper.java:230)
    at com.amazon.sqs.javamessaging.SQSSession.createQueue(SQSSession.java:576)
    at com.hivehome.kafka.connect.sqs.SQSConsumer$.createSQSConsumer(SQSConsumer.scala:26)
    at com.hivehome.kafka.connect.sqs.SQSConsumer$.apply(SQSConsumer.scala:13)
    at com.hivehome.kafka.connect.sqs.SQSSourceTask.liftedTree1$1(SQSSourceTask.scala:51)
    at com.hivehome.kafka.connect.sqs.SQSSourceTask.start(SQSSourceTask.scala:50)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:137)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.sqs.model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. (Service: AmazonSQS; Status Code: 400; Error Code: AWS.SimpleQueueService.NonExistentQueue; Request ID: 5b202ca5-450d-5ab7-868c-7c55e4884966)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
    at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
    at com.amazonaws.services.sqs.AmazonSQSClient.doInvoke(AmazonSQSClient.java:1663)
    at com.amazonaws.services.sqs.AmazonSQSClient.invoke(AmazonSQSClient.java:1639)
    at com.amazonaws.services.sqs.AmazonSQSClient.getQueueUrl(AmazonSQSClient.java:988)
    at com.amazon.sqs.javamessaging.AmazonSQSMessagingClientWrapper.getQueueUrl(AmazonSQSMessagingClientWrapper.java:260)
```

**Comment by skate056** [comment]
Can you check if AWS credentials have access to write to the SQS queue? I got a similar error when the key/secret did not have access to the queue.

**Comment by mina-qlik** [comment]
@skate056 My AWS credentials have admin permission and I am only reading from SQS not writing. Therefore, the error that I am getting is not related to AWS credential access.

**Comment by nbarbey** [comment]
I have a very similar problem. Using aws cli version aws-cli/1.4.2 Python/3.4.2 Linux/3.16.0-4-amd64 available on debian 8.5 I reproduce the error message.
But, using aws cli version aws-cli/1.11.73 Python/2.7.9 Linux/3.16.0-4-amd64 botocore/1.5.36 as installed with pip, the error disappear.
Thus I wonder if the problem could be related to the version of the AWS authentication protocol ?
What version of authentication is supported by sqs-kafka-connect ?
I also have the extra complexity of having to handle a profile. Does sqs-kafka-connect handles profiles (through ~/.aws/config or environement variables) ?

Anyway I want to thank you for providing this piece of software which could prove quite useful to me if I manage to sort out this issue.
